name: Test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pip-tools build
        pip-compile -o requirements.txt pyproject.toml
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --statistics
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build project
      run: python -m build
